# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2016/11/30/setting-up-gitlab-ci-for-android-projects/, by Greyson Parrelli
image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "26.0.2"
  ANDROID_SDK_TOOLS: "26.1.0"

stages:
  - build
  - test
  - package


####################################################################################################
# BUILD
#
.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 4 hours
    paths:
    - app/build/outputs/
    - .android/

  before_script:
    # Extract the SDK version that we're building against
    - export ANDROID_COMPILE_SDK=`egrep '^[[:blank:]]+compileSdkVersion'  app/build.gradle | awk '{print $2}'`

    # Explict output for logging purpose only
    - echo $ANDROID_SDK_TOOLS
    - echo $ANDROID_COMPILE_SDK

    # Fetch the specified SDK tools version to build with
    - apt-get --quiet install --yes locales wget zip unzip lib32stdc++6 lib32z1
    - wget --quiet --output-document=tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
    - unzip -q tools.zip
    - rm -fr $ANDROID_HOME tools.zip
    - mkdir -p $ANDROID_HOME
    - mv tools $ANDROID_HOME/tools
    # Fix gradle 3.0 problem
    - mkdir --parents /root/.android && touch /root/.android/repositories.cfg
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;android;m2repository"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;google;google_play_services"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;google;m2repository"
    - wget --quiet --output-document=android-ndk.zip http://dl.google.com/android/repository/android-ndk-r${ANDROID_NDK_VERSION}-linux-x86_64.zip
    - unzip -q android-ndk.zip
    - rm -fr ANDROID_NDK_HOME android-ndk.zip
    - mv android-ndk-r${ANDROID_NDK_VERSION} ANDROID_NDK_HOME
    - export ANDROID_SDK_HOME=$ANDROID_HOME
    - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/android-ndk
    - chmod +x ./gradlew

    stages:
    - build
    - test

    build:
    stage: build
    script:
      - ./gradlew assemble
    artifacts:
      paths:
      - app/build/outputs/

    unitTests:
      stage: test
      script:
      - ./gradlew test
